Repository voxel51/pandemic51, pull requests merged in 2020-03, with the labels that each got.

#47 Handle Skip Empty-case
  pandemic51/core/pdi.py
Labels: bug

#48 Usability tweaks
  web/src/components/footer.js
  web/src/components/header.js
  web/src/styles/global.css
Labels: enhancement

#57 Y-axis Centered Header
  web/src/components/header.js
Labels: enhancement

#58 MySQL shortcut bug
  README.md
Labels: bug

#54 Latest web updates
  web/gatsby-config.js
  web/package.json
  web/src/components/bigChart.js
  web/src/components/chart.js
  web/src/components/cityCard.js
  web/src/components/footer.js
  web/src/components/header.js
  web/src/components/help.js
  web/src/components/imageOverlay.js
  web/src/components/layout.js
  web/src/components/mobileCityCard.js
  web/src/components/pd.js
  web/src/components/player.js
  web/src/components/sb.js
  web/src/components/seo.js
  web/src/pages/index.js
  web/src/styles/global.css
  web/yarn.lock
Labels: enhancement, mobile

#62 Proper arg passing to `pymysql` `cursor.execute()`
  pandemic51/core/database.py
Labels: enhancement

#63 Make images on mobile show on touch-end events
  web/src/components/chart.js
  web/src/components/layout.js
Labels: enhancement, mobile

#59 Update README to install chromedriver
  README.md
  scripts/linux_preinstall.bash
Labels: dependencies, documentation

#65 Add GitHub icon to button
  web/src/components/footer.js
Labels: enhancement

#66 Fall back to native video if MediaSource is not supported (iOS)
  web/src/components/player.js
Labels: bug
