Repository voxel51/pandemic51, pull requests merged in 2020-04, with the labels that each got.

#71 Events fix
  pandemic51/core/events.py
Labels: bug, enhancement

#73 Show tooltips in a specified radius of the event
  pandemic51/core/events.py
Labels: enhancement

#75 Add timestamps to image overlay
  web/src/components/chart.js
  web/src/components/imageOverlay.js
  web/src/components/layout.js
  web/src/styles/global.css
Labels: enhancement

#69 Switching to on hover for image overlay
  web/gatsby-config.js
  web/src/components/bigChart.js
  web/src/components/chart.js
  web/src/components/cityCard.js
  web/src/components/header.js
  web/src/components/help.js
  web/src/components/imageOverlay.js
  web/src/components/layout.js
  web/src/components/player.js
  web/src/components/seo.js
  web/src/styles/global.css
  web/static/newyork.jpg
Labels: question

#78 Indicate selected time on graph
  web/src/components/chart.js
  web/src/components/layout.js
Labels: enhancement

#74 Events API fix
  pandemic51/core/events.py
Labels: bug

#76 Backup commands
  README.md
Labels: documentation

#82 Historical data script only uploads images
  scripts/add_historical_to_db.py
Labels: enhancement

#81 Add support for permalinking to times
  web/package.json
  web/src/components/bigChart.js
  web/src/components/chart.js
  web/src/components/cityCard.js
  web/src/components/imageOverlay.js
  web/src/components/layout.js
  web/src/components/mobileCityCard.js
  web/src/pages/lasvegas.js
  web/src/styles/global.css
  web/yarn.lock
Labels: enhancement

#84 Serializable `Stream` object
  config/config-template.py
  config/streams.json
  config/streams/abbey_road.json
  config/streams/ann_arbor.json
  config/streams/chicago.json
  config/streams/detroit.json
  config/streams/dublin.json
  config/streams/fort_lauderdale.json
  config/streams/las_vegas.json
  config/streams/new_jersey.json
  config/streams/new_orleans.json
  config/streams/prague.json
  config/streams/time_square.json
  config/streams/ypsilanti.json
  pandemic51/core/api.py
  pandemic51/core/streaming.py
  pandemic51/core/tasks.py
  scripts/add_historical_to_db.py
  tests/download_and_store/test_download_and_store.py
  tests/start/download_stream.py
  tests/stream/.gitignore
  tests/stream/example_image_stream_download.py
  tests/stream/example_mjpg_stream_download.py
  tests/stream/test_download_and_store.py
Labels: enhancement

#88 Omit beta streams from average
  config/config-template.py
  pandemic51/core/api.py
Labels: enhancement

#91 Update thresholds
  config/config-template.py
  pandemic51/core/api.py
  pandemic51/core/database.py
  pandemic51/core/detections.py
  tests/pdi/compute_object_counts.py
Labels: enhancement

#90 Add support for YouTube streams
  pandemic51/core/streaming.py
  requirements.txt
  tests/stream/test_youtube.py
  tests/stream/youtube-test.json
Labels: enhancement

#98 I swear I know how to spell "always"
  config/streams/abbey_road.json
  config/streams/brighton.json
  config/streams/chicago.json
  config/streams/dublin.json
  config/streams/fort_lauderdale.json
  config/streams/las_vegas.json
  config/streams/miami.json
  config/streams/new_jersey.json
  config/streams/new_orleans.json
  config/streams/prague.json
  config/streams/time_square.json
  pandemic51/core/streaming.py
Labels: bug, enhancement

#77 Analysis Notebook for blog
  analysis/counts.csv
  analysis/pdi_analysis.ipynb
  requirements.txt
  scripts/db2csv.py
Labels: documentation, enhancement

#97 Face redaction
  pandemic51/core/api.py
  pandemic51/core/detections.py
  pandemic51/core/streaming.py
  tests/detections/run_redacttest.bash
  tests/detections/test_redaction.py
  web/src/components/chart.js
Labels: feature

#100 Frame navigation
  web/src/components/chart.js
  web/src/components/imageOverlay.js
  web/src/components/layout.js
  web/src/components/mobileCityCard.js
  web/src/styles/global.css
Labels: feature

#101 Add hollywood stream
  config/streams/hollywood.json
Labels: feature

#103 Add Atlanta Stream
  config/streams/atlanta.json
Labels: feature
